import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider"
import { useTheme } from "next-themes";
// import { RecoilRoot } from "recoil";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const { setTheme } = useTheme();
  // setTheme("dark")
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <RecoilRoot> */}
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
        {/* </RecoilRoot> */}
      </body>
    </html>
  );
}
